art_cloud/urls.py
# Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^admin/', include(admin.site.urls)),
	(r'^wiki/', include('wiki.urls')),
	(r'^datonomy/', include('datonomy.urls')),
	(r'^alert/', include('pokepoke.urls')),
	(r'^epoxy/', include('epoxy.urls')),
	(r'^clue/', include('clue.urls')),
	(r'^audio/', include('malleus.urls')),
	(r'^api/audio/', include('malleus.api_urls')),
	(r'^api/alert/', include('pokepoke.api_urls')),
	(r'^api/phone/', include('phonon.api_urls')),
	(r'^api/front/', include('front.api_urls')),
	(r'^', include('front.urls')),
)

art_cloud/wiki/urls.py
# Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
from django.conf.urls.defaults import *
from django.conf import settings
 
urlpatterns = patterns('',
	(r'^$', 'wiki.views.index'),
	(r'(?P<name>[^/]+)/history/(?P<id>[^/]+)$' , 'wiki.views.wiki_page_log'),
	(r'(?P<name>[^/]+)/history/$' , 'wiki.views.wiki_history'),
	(r'(?P<name>[^/]+)/photo/(?P<id>[\d]+)/$' , 'wiki.views.photo'),
	(r'(?P<name>[^/]+)/file/(?P<id>[\d]+)/$' , 'wiki.views.file'),
	(r'(?P<name>[^/]+)/add/$' , 'wiki.views.wiki_add'),
	(r'(?P<name>[^/]+)/edit/$' , 'wiki.views.wiki_edit'),
	(r'(?P<name>[^/]+)/print/$' , 'wiki.views.wiki_print'),
	(r'print-all/$' , 'wiki.views.wiki_print_all'),
	(r'photo/(?P<id>[\d]+)/$' , 'wiki.views.photo_redirect'),
	(r'photo-detail/(?P<id>[\d]+)/$' , 'wiki.views.photo_detail_redirect'),
	(r'(?P<name>[^/]+)/$', 'wiki.views.wiki'),
)

art_cloud/wiki/models.py
# Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
import os
import os.path
import urllib
import datetime, calendar
import re
import feedparser
import unicodedata
import traceback
import logging
import pprint

from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.sites.models import Site

from art_cloud.abstract_models import ThumbnailedModel
from templatetags.wikitags import wiki

class WikiPageManager(models.Manager):
	def get_or_create(self, name):
		try: return WikiPage.objects.get(name=name)
		except: return WikiPage(name=name)

class WikiPage(models.Model):
	"""A named chunk of markdown formatted text."""
	name = models.CharField(max_length=255, unique=True, blank=False, null=False)
	content = models.TextField(blank=False, null=False)
	rendered = models.TextField(blank=True, null=True)
	public = models.BooleanField(default=True)
	objects = WikiPageManager()
	@models.permalink
	def get_absolute_url(self):
		if self.name == "SplashPage": return ('wiki.views.index', [], {})
		return ('wiki.views.wiki', [], { 'name':self.name })
	@models.permalink
	def get_edit_url(self):
		return ('wiki.views.wiki_edit', [], { 'name':self.name })
	def __unicode__(self):
		return self.name
	def save(self, *args, **kwargs):
		"""When saving the content, render via markdown and save to self.rendered"""
		self.rendered = wiki(self.content)
		super(WikiPage, self).save(*args, **kwargs)
		WikiPageLog.objects.create(wiki_page=self, content=self.content)
	class Meta:
		ordering = ('name',)

class WikiPageLog(models.Model):
	"""A historical version of a WikiPage."""
	wiki_page = models.ForeignKey(WikiPage, blank=False, null=False)
	content = models.TextField(blank=False, null=False)
	created = models.DateTimeField(auto_now_add=True)
	@models.permalink
	def get_absolute_url(self):
		return ('wiki.views.wiki_page_log', [], { 'name':self.wiki_page.name, 'id':self.id })
	def __unicode__(self):
		return '%s: %s' % (self.wiki_page.name, self.created)
	class Meta:
		ordering = ('-created',)

class WikiConstant(models.Model):
	"""A piece of wikitext which can be included (but not wiki rendered) in multiple wiki pages
	The syntax is \%constant_name\%
	"""
	name = models.CharField(max_length=512, null=False, blank=False)
	constant = models.TextField(blank=False, null=False)
	def __unicode__(self):
		return self.name

class WikiFile(models.Model):
	"""A non-image file associated with a WikiPage."""
	file = models.FileField(upload_to='wiki_file', blank=False, null=False)
	wiki_page = models.ForeignKey(WikiPage, blank=False, null=False)
	title = models.CharField(max_length=1024, null=True, blank=True)
	description = models.TextField(blank=True, null=True)
	created = models.DateTimeField(auto_now_add=True)
	def display_name(self):
		if self.title: return self.title
		return os.path.basename(self.file.name)
	@models.permalink
	def get_absolute_url(self):
		return ('wiki.views.file', (), { 'name':self.wiki_page.name, 'id':self.id })
	class Meta:
		ordering = ['-created']
	def __unicode__(self):
		return str(self.file)

class WikiPhoto(ThumbnailedModel):
	"""An image and metadata associated with a WikiPage."""
	image = models.ImageField(upload_to='wiki_photo', blank=False)
	wiki_page = models.ForeignKey(WikiPage, blank=False, null=False)
	title = models.CharField(max_length=1024, null=True, blank=True)
	caption = models.CharField(max_length=1024, null=True, blank=True)
	description = models.TextField(blank=True, null=True)
	created = models.DateTimeField(auto_now_add=True)
	def display_name(self):
		if self.title: return self.title
		return os.path.basename(self.image.name)
	@models.permalink
	def get_absolute_url(self):
		return ('wiki.views.photo', (), { 'name':self.wiki_page.name, 'id':self.id })
	class Meta:
		ordering = ['-created']
	def __unicode__(self):
		return str(self.image)

art_cloud/wiki/forms.py
# Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
from django import forms
from django.contrib.auth.models import User
from django.utils.html import strip_tags

from models import *

class WikiPageForm(forms.ModelForm):
	class Meta:
		model = WikiPage
		fields = ('content',)

class WikiFileForm(forms.ModelForm):
	class Meta:
		model = WikiFile
		fields = ('file','title','description')

class WikiPhotoForm(forms.ModelForm):
	class Meta:
		model = WikiPhoto
		fields = ('image','title','description')

art_cloud/wiki/views.py
# Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
import datetime
import calendar
import pprint
import traceback

from django.conf import settings
from django.db.models import Q
from django.template import Context, loader
from django.http import HttpResponse, Http404, HttpResponseServerError, HttpResponseRedirect, HttpResponsePermanentRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.comments.models import Comment
from django.contrib.sites.models import Site
from django.utils.html import strip_tags
import django.contrib.contenttypes.models as content_type_models
from django.template import RequestContext
from django.core.cache import cache
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.template.loader import render_to_string
from django.utils import feedgenerator
from django.core.urlresolvers import reverse

from models import *
from forms import *

@login_required
def index(request):
	page = WikiPage.objects.get_or_create(name='SplashPage')
	return render_to_response('wiki/index.html', { 'wiki_pages':WikiPage.objects.all(), 'page':page }, context_instance=RequestContext(request))

@login_required
def photo_redirect(request, id):
	photo = get_object_or_404(WikiPhoto, pk=id)
	return HttpResponseRedirect(photo.image.url)

@login_required
def photo_detail_redirect(request, id):
	photo = get_object_or_404(WikiPhoto, pk=id)
	return HttpResponseRedirect(photo.get_absolute_url())

@login_required
def photo(request, name, id):
	photo = get_object_or_404(WikiPhoto, wiki_page__name=name, pk=id)
	return render_to_response('wiki/photo.html', { 'photo':photo }, context_instance=RequestContext(request))

@login_required
def file(request, name, id):
	file = get_object_or_404(WikiFile, wiki_page__name=name, pk=id)
	return render_to_response('wiki/file.html', { 'file':file }, context_instance=RequestContext(request))

@login_required
def wiki(request, name):
	page = WikiPage.objects.get_or_create(name=name)
	if not page.id: return HttpResponseRedirect(page.get_edit_url())
	if request.method == 'POST' and request.user.is_staff:
	    if request.POST.get('public', None):
	        if request.POST.get('public') == 'true': page.public = True
	        if request.POST.get('public') == 'false': page.public = False
	        page.save()
	        
	return render_to_response('wiki/wiki.html', { 'page':page }, context_instance=RequestContext(request))

@login_required
def wiki_print(request, name):
	page = WikiPage.objects.get_or_create(name=name)
	if not page.id: return HttpResponseRedirect(page.get_edit_url())
	return render_to_response('wiki/wiki_print.html', { 'page':page }, context_instance=RequestContext(request))

@login_required
def wiki_print_all(request):
	return render_to_response('wiki/wiki_print_all.html', { 'pages':WikiPage.objects.all() }, context_instance=RequestContext(request))

@login_required
def wiki_add(request, name):
	page = WikiPage.objects.get_or_create(name=name)
	if request.method == 'POST' and request.user.is_authenticated:
		wiki_photo_form = WikiPhotoForm(request.POST, request.FILES)
		wiki_file_form = WikiFileForm(request.POST, request.FILES)
		if request.POST.get('photo-form', None):
			# remove any non-unicode file name characters
			raw_photo = request.FILES.get('image', None)
			if raw_photo:
				raw_photo.name = raw_photo.name.encode('ascii', 'ignore')
				wiki_photo_form = WikiPhotoForm(request.POST, request.FILES)

			if wiki_photo_form.is_valid():
				photo = wiki_photo_form.save(commit=False)
				if not page.id: page.save()
				photo.wiki_page = page
				photo.save()
				page.content = "%s\n\nPhoto%s" % (page.content, photo.id)
				page.save()
				return HttpResponseRedirect(page.get_edit_url())
			wiki_file_form = WikiFileForm()

		elif request.POST.get('file-form', None):
			# remove any non-unicode file name characters
			raw = request.FILES.get('file', None)
			if raw: raw.name = raw.name.encode('ascii', 'ignore')
			wiki_file_form = WikiFileForm(request.POST, request.FILES)

			if wiki_file_form.is_valid():
				file = wiki_file_form.save(commit=False)
				if not page.id: page.save()
				file.wiki_page = page
				file.save()
				return HttpResponseRedirect(page.get_edit_url())
			wiki_photo_form = WikiPhotoForm()
		else:
			print request.POST
	else:
		wiki_photo_form = WikiPhotoForm()
		wiki_file_form = WikiFileForm()
	return render_to_response('wiki/wiki_add.html', { 'page':page, 'wiki_photo_form':wiki_photo_form, 'wiki_file_form':wiki_file_form }, context_instance=RequestContext(request))

@login_required
def wiki_history(request, name):
	return render_to_response('wiki/wiki_history.html', { 'page':WikiPage.objects.get_or_create(name=name) }, context_instance=RequestContext(request))

@login_required
def wiki_page_log(request, name, id):
	page_log = get_object_or_404(WikiPageLog, wiki_page__name=name, pk=id)
	if request.method == 'POST' and request.POST.get('revert', None) and request.user.is_authenticated:
		page_log.wiki_page.content = page_log.content
		page_log.wiki_page.save()
		return HttpResponseRedirect(page_log.wiki_page.get_absolute_url())
	return render_to_response('wiki/wiki_page_log.html', { 'page_log':page_log  }, context_instance=RequestContext(request))

@login_required
def wiki_edit(request, name):
	page = WikiPage.objects.get_or_create(name=name)
	if request.method == 'POST' and request.user.is_authenticated:
		page_form = WikiPageForm(request.POST, instance=page)
		if page_form.is_valid():
			if not page.id: page.public = True
			page = page_form.save()
			if request.GET.get('next', None): return HttpResponseRedirect(request.GET.get('next'))
			return HttpResponseRedirect(page.get_absolute_url())
	else:
		page_form = WikiPageForm(instance=page)
	return render_to_response('wiki/wiki_edit.html', { 'page':page, 'page_form':page_form }, context_instance=RequestContext(request))

art_cloud/wiki/templates/wiki/base.html
{% extends "art_cloud/base.html" %}

{% block style %}
.wiki-photo-item { display: inline; width: 160px; height: 170px; }

.rendered-page { margin: 20px 0px; border-bottom: solid 1px #DDD; }
.rendered-page em { font-weight: bold; }
.rendered-page hr { margin: 20px 0px; }
.rendered-page li { margin: 0px 0px 10px 20px; }
.rendered-page h1, .rendered-page h2, .rendered-page h3, .rendered-page h4, .rendered-page h5 { color: #000; }
.rendered-page code { white-space:pre; font-family: monospace; }
.wiki-control-links { float: right; margin-top: 5px; }
.wiki-control-links a { font-size: 0.8em; }
.wiki-control-links form { display: inline; margin-right: 15px; }
.printed-page { border-bottom: none; }
.printed-page a { text-decoration: none; color: #000; }
.printed-page h1 a { color: #000; font-size: 1.2em; }
{% block sub-style%}{% endblock %}
{% endblock %}

art_cloud/wiki/templates/wiki/file.html
{% extends "wiki/base.html" %}

{% block sub-title %}{{ file.display_name }} | {% endblock %}

{% load imagetags %}
{% block content %}
<h1>File on <a href="{{ file.wiki_page.get_absolute_url }}">{{ file.wiki_page.name }}</a>: {{ file.display_name }}</h1>

<table>
	{% if file.description %}
	<tr>
		<th>description:</th>
		<td>{{ file.description }}</td>
	</tr>
	{% endif %}
	{% if file.created %}
	<tr>
		<th>created:</th>
		<td>{{ file.created }}</td>
	</tr>
	{% endif %}
	<tr>
		<th>original file:</th>
		<td><a href="{{ file.file.url }}">{{ file.file.url }}</a></td>
	</tr>
</table>

{% endblock %}

art_cloud/wiki/templates/wiki/index.html
{% extends "wiki/base.html" %}
{% load wikitags %}
{% block sub-title %}Notes | {% endblock %}

{% block sub-style %}
#left-column { 
	width: 140px; 
	border-right: solid 1px #DDD;
}
#left-column li { list-style: none; margin-left: 0px; }
#main-column {
	width: 650px;
	float: right;
}
{% endblock %}

{% block content %}
<h1>Notes:</h1>
<div id="main-column">
	{% with "true" as hide_title %}{% with "true" as hide_public %}{% include "wiki/wiki_render.frag" %}{% endwith %}{% endwith %}
</div>
<div id="left-column">
	<h4>Page Index:</h4>
	<ul>
	{% for page in wiki_pages %}
	   {% if page.public or request.user.is_staff %}
		   <li><a title="{{ page.name }}" href="{{ page.get_absolute_url }}">{{ page.name|truncate:"18" }}</a></li>
		{% endif %}
	{% endfor %}
	</ul>
	{% if wiki_pages %}
	   <h4>Quicklinks:</h4>
	   <ul>
	      <li><a href="{% url wiki.views.wiki_print_all %}">printable all-in-one</a></li>
	      {% if request.user.is_staff %}
	         <li><a href="{% url admin:app_list 'wiki' %}">notes admin</a></li>
	      {% endif %}
	   </ul>
	{% endif %}
</div>
{% endblock %}

art_cloud/wiki/templates/wiki/photo.html
{% extends "wiki/base.html" %}

{% block sub-title %}{{ photo.display_name }} | {% endblock %}

{% load imagetags %}
{% block content %}
<h1>Photo on <a href="{{ photo.wiki_page.get_absolute_url }}">{{ photo.wiki_page.name }}</a>: {{ photo.display_name }}</h1>

<img style="margin-bottom: 20px; " src="{{ photo.image.url|fit_image:"600x600" }}" />

<table>
	{% if photo.caption %}
	<tr>
		<th>caption:</th>
		<td>{{ photo.caption }}</td>
	</tr>
	{% endif %}
	{% if photo.description %}
	<tr>
		<th>description:</th>
		<td>{{ photo.description }}</td>
	</tr>
	{% endif %}
	{% if photo.created %}
	<tr>
		<th>created:</th>
		<td>{{ photo.created }}</td>
	</tr>
	{% endif %}
	<tr>
		<th>original file:</th>
		<td><a href="{{ photo.image.url }}">{{ photo.image.url }}</a></td>
	</tr>
</table>

{% endblock %}

art_cloud/wiki/templates/wiki/wiki.html
{% extends "wiki/base.html" %}

{% block sub-title %}{{ page.name }} | {% endblock %}

{% block content %}
   {% include "wiki/wiki_render.frag" %}
{% endblock %}

art_cloud/wiki/templates/wiki/wiki_add.html
{% extends "wiki/base.html" %}

{% block style %}
#wiki-file-form, #wiki-photo-form { width: 400px; margin-bottom: 40px; }
#wiki-file-form input[type=submit], #wiki-photo-form input[type=submit] { float: right; }
{% endblock %}

{% block content %}
<h1>Add Files or Photos to <a href="{{ page.get_absolute_url }}">{{ page.name }}</a>:</h1>

<h2>Add a file:</h2>
<form id="wiki-file-form" enctype="multipart/form-data" action="" method="post">
	<table>
	{{ wiki_file_form }}
	</table>
	<input type="hidden" name="file-form" value="true" />
	<input type="submit" value="add file" />
	{% csrf_token %}
</form>

<h2>Add a photo:</h2>
<form id="wiki-photo-form" enctype="multipart/form-data" action="" method="post">
	<table>
	{{ wiki_photo_form }}
	</table>
	<input type="hidden" name="photo-form" value="true" />
	<input type="submit" value="add photo" />
	{% csrf_token %}
</form>

{% endblock %}

art_cloud/wiki/templates/wiki/wiki_edit.html
{% extends "wiki/base.html" %}
{% load imagetags %}

{% block sub-title %}Edit | {{ page.name }} | {% endblock %}

{% block style %}
#id_content { width: 100%; height: 400px; }
#page-form { margin-bottom: 10px; float: left; width: 620px; }
#page-form input[type=submit] { float: right; }
.wiki-photo-item { margin-top: 10px; }
#cheat-sheet { float: right; width: 150px; border: dashed 1px #DDD; padding: 0 10px; color: #666; }
{% endblock %}

{% block sub-head %}
<script type="text/javascript">
function saveThenAddFile(){
	$("#page-form").attr('action', '.?next={% url wiki.views.wiki_add page.name %}');
	$("#page-form").submit();
}
</script>
{% endblock %}

{% block content %}
<h1>Edit Page: <a href="{{ page.get_absolute_url }}">{{ page.name }}</a></h1>

<div id="cheat-sheet">
	<h3>Cheat Sheet:</h3>
	<h4>Links:</h4>
	CamelCase to link to a note.
	
	<h4>Lists:</h4>
	- Apples<br/>
	- Oranges<br/>
	- Aesthetics<br/>
	<br/>
	or<br/>
	<br/>
	1. Apples<br/>
	2. Oranges<br/>
	3. Handcarts<br/>

	<h4>Headings:</h4>
	#Biggest<br/>
	##Second Biggest<br/>
	###Third Biggest<br/>
	
	<h4>Links:</h4>
	[text](address "title")
	
	<h4>Horizontal Rules:</h4>
	***
	
	<p>[<a href="{% url wiki.views.index %}WikiHelp">more help</a>]</p>
</div>

{% if not page.public and not request.user.is_staff %}
   <p>This page is not public.</p>
{% else %}
   <form id="page-form" action="." method="post">
   	{% for field in page_form %}{{ field }}{% endfor %}
   	<input type="submit" value="save" />
	{% csrf_token %}
   </form>
   <br clear="all" />
   <div class="wiki-control-links">[<a onclick="saveThenAddFile(); return false;" href="{% url wiki.views.wiki_add page.name %}">add file or photo</a>]</div>

   {% if page.wikiphoto_set.all %}
   <h3>Photos:</h3>
   <p>To include a photo in the page, type a photo tag which starts with "Photo" and ends with the photo id, like so "Photo5".<br/>  You will find the photo tag above each photo listed below.</p>
   {% endif %}
   {% for photo in page.wikiphoto_set.all %}
   	<div class="wiki-photo-item">
   		Photo{{ photo.id }}<br/>
   		<a href="{{ photo.get_absolute_url }}">
   			<img alt="{{ photo.display_name }}" title="{{ photo.display_name }}" src="{{ photo.image.url|fit_image:"150x150" }}" /> 
   		</a>
   	</div>
   {% endfor %}

   {% if page.wikifile_set.all %}
   <h3>Files:</h3>
   {% endif %}
   {% for file in page.wikifile_set.all %}
   	<div class="wiki-file-item">
   		<a href="{{ file.file.url }}">{{ file.display_name }}</a> <span class="wiki-control-link">[<a href="{{ file.get_absolute_url }}">info</a>]</span>
   	</div>
   {% endfor %}
{% endif %}
{% endblock %}

art_cloud/wiki/templates/wiki/wiki_history.html
{% extends "wiki/base.html" %}

{% block sub-title %}History | {{ page.name }} | {% endblock %}

{% block style %}
.wiki-page-log-item { margin: 10px 10px;}
{% endblock %}

{% block content %}
<h1>History: {{ page }}</h1>

{% for log in page.wikipagelog_set.all %}
{% ifchanged log.created.day %}
	<h3>{{ log.created|date:"F j"}}:</h3>
{% endifchanged %}
<div class="wiki-page-log-item">
	<a href="{{ log.get_absolute_url }}">{{ log.created|date:"g:i A" }}</a>
</div>
{% endfor %}
{% endblock %}

art_cloud/wiki/templates/wiki/wiki_page_log.html
{% extends "wiki/base.html" %}
{% load wikitags %}

{% block sub-title %}Snapshot {{ page_log.created|date:"F j, g:i A"}} | {{ page_log.wiki_page.name }} | {% endblock %}

{% block style %}
#id_content { width: 100%; height: 400px; }
{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}
	<div style="float: right; margin-top: 5px; ">
			[<a href="." onclick="document.getElementById('revert-form').submit(); return false;">revert to this version</a>]
			<form id="revert-form" action="{{ page_log.get_absolute_url }}" method="post"><input type="hidden" name="revert" value="true">{% csrf_token %}</form>
	</div>
{% endif %}
<h1>Snapshot of <a href="{{ page_log.wiki_page.get_absolute_url }}">{{ page_log.wiki_page.name }}</a> at {{ page_log.created|date:"F j, g:i A"}}:</h1>

{{ page_log.content|wiki|safe }}

{% endblock %}

art_cloud/wiki/templates/wiki/wiki_print.html
{% extends "wiki/base.html" %}

{% block title %}{{ page.name }}{% endblock %}

{% block header %}{% endblock %}
{% block content %}
	{% include "wiki/wiki_print_render.frag" %}
{% endblock %}

art_cloud/wiki/templates/wiki/wiki_print_all.html
{% extends "wiki/base.html" %}

{% block title %}{{ site.name }} Wiki{% endblock %}
{% block style %}
.page-breaker { margin-bottom: 30px; page-break-after: always; }
{% endblock %}
{% block header %}{% endblock %}
{% block content %}
{% for page in pages %}
   {% if page.public or request.user.is_staff %}
	   {% include "wiki/wiki_print_render.frag" %}
	   <hr class="page-breaker" />
	{% endif %}
{% endfor %}
{% endblock %}