art_cloud/front/urls.py
# Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
from django.conf.urls.defaults import *
from django.conf import settings

from piston.resource import Resource
import piston.emitters
from handlers import WeatherHandler, AirportObservationHandler, ICAOAirportObservationHandler

from models import *

class PlainTextEmitter(piston.emitters.Emitter):
	""" Piston Emitter for plain text. """
	def render(self, request, format='plain_text'):
		return self.data
piston.emitters.Emitter.register('plain_text', PlainTextEmitter, 'text/plain')

weather_resource = Resource(handler=WeatherHandler)
airport_observation_resource = Resource(handler=AirportObservationHandler)
icao_airport_observation_resource = Resource(handler=ICAOAirportObservationHandler)

urlpatterns = patterns('',
   url(r'^api/weather/(?P<zip_code>[\d]+).xml$', weather_resource, { 'emitter_format': 'xml' }), 
   url(r'^api/weather/airport/(?P<airport_code>[^/]+).xml$', airport_observation_resource, { 'emitter_format': 'string2xml' }), 
   url(r'^api/weather/icao-airport/(?P<airport_code>[^/]+).txt$', icao_airport_observation_resource, { 'emitter_format': 'plain_text' }), 

	(r'^photo/(?P<id>[\d]+)/$', 'art_cloud.front.views.photo_detail'),
	(r'^equipment-type/(?P<id>[\d]+)/$', 'art_cloud.front.views.equipment_type_detail'),
	(r'^equipment/(?P<id>[\d]+)/$', 'art_cloud.front.views.equipment_detail'),
	(r'^installation-site/(?P<id>[\d]+)/$', 'art_cloud.front.views.installation_site_detail'),
	(r'^installation/(?P<id>[\d]+)/$', 'art_cloud.front.views.installation_detail'),
	(r'^installation/(?P<id>[\d]+)/heartbeat/$', 'art_cloud.front.views.installation_heartbeats'),
	(r'^installation/(?P<id>[\d]+)/heartbeat/csv/$', 'art_cloud.front.views.installation_heartbeats_csv'),
	(r'^installation/(?P<slug>[^/]+)/$', 'art_cloud.front.views.installation_detail_slug'),
	(r'^profile/(?P<username>[^/]+)/$', 'art_cloud.front.views.profile_detail'),
	(r'^tag/(?P<name>[^/]+)/$', 'art_cloud.front.views.tag'),
	(r'^tag/$', 'art_cloud.front.views.tags'),
	(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'front/login.html'}),
	(r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login'),
	(r'^accounts/profile/$', 'django.views.generic.simple.redirect_to', {'url': '/'}),
	(r'^heartbeat/$', 'art_cloud.front.views.heartbeats'),
	(r'^group/(?P<id>[\d]+)$', 'art_cloud.front.views.artist_group_detail'),
	(r'^search/$', 'art_cloud.front.views.search'),

	(r'^installation-slice/$', 'art_cloud.front.views.installation_slice'),
	(r'^artist-slice/$', 'art_cloud.front.views.artist_slice'),
	(r'^site-slice/$', 'art_cloud.front.views.site_slice'),
	(r'^$', 'art_cloud.front.views.index'),

	(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

art_cloud/urls.py
# Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^admin/', include(admin.site.urls)),
	(r'^wiki/', include('wiki.urls')),
	(r'^datonomy/', include('datonomy.urls')),
	(r'^alert/', include('pokepoke.urls')),
	(r'^epoxy/', include('epoxy.urls')),
	(r'^clue/', include('clue.urls')),
	(r'^audio/', include('malleus.urls')),
	(r'^api/audio/', include('malleus.api_urls')),
	(r'^api/alert/', include('pokepoke.api_urls')),
	(r'^api/phone/', include('phonon.api_urls')),
	(r'^api/front/', include('front.api_urls')),
	(r'^', include('front.urls')),
)

art_cloud/front/models.py
# Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
import os
import os.path
import Image
import urllib
import datetime, calendar
import random
import time
import re
import feedparser
import unicodedata
import traceback
import logging
import pprint

from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.db import models
from django.db.models import signals
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.dispatch import dispatcher
from django.core.mail import send_mail
from django.utils.encoding import force_unicode
from django.db.models import Q

from art_cloud.abstract_models import ThumbnailedModel
from tagging.models import Tag
from datonomy.models import NamedDate

from hydration import HydrationEmitter # this sets the piston emitters

class ArtistGroupManager(models.Manager):
	def search(self, search_string):
		terms = normalize_search_string(search_string)
		if len(terms) == 0: return None;
		name_query = ArtistGroup.objects.filter(name__icontains=terms[0])
		for term in terms[1:]:
			name_query = name_query & ArtistGroup.objects.filter(name__icontains=term)
		search_query = name_query
		return search_query.order_by('name')

class ArtistGroup(models.Model):
	"""A group of artists who collectively create installations, perhaps also with individual artists."""
	name = models.CharField(max_length=1024, blank=False, null=False)
	artists = models.ManyToManyField(User, blank=False, null=False)
	url = models.URLField(verify_exists=False, blank=True, null=True, max_length=1024)
	objects = ArtistGroupManager()
	class Meta:
		ordering = ['name']
	@models.permalink
	def get_absolute_url(self):
		return ('art_cloud.front.views.artist_group_detail', (), { 'id':self.id })
	class HydrationMeta:
		attributes = ['id', 'name', 'url']
		nodes = ['artists']
	def __unicode__(self):
		return self.name

class Photo(ThumbnailedModel):
	"""An image with some metadata to be associated with multiple types of models."""
	image = models.ImageField(upload_to='photo', blank=False)
	title = models.CharField(max_length=1024, null=True, blank=True)
	caption = models.CharField(max_length=1024, null=True, blank=True)
	description = models.TextField(blank=True, null=True)
	created = models.DateTimeField(auto_now_add=True)
	def display_name(self):
		if self.title: return self.title
		return os.path.basename(self.image.name)
	@models.permalink
	def get_absolute_url(self):
		return ('art_cloud.front.views.photo_detail', (), { 'id':self.id })
	class Meta:
		ordering = ['-created']
	class HydrationMeta:
		attributes = ['id', 'title', 'caption', 'created']
		nodes = ['description', 'image']
	def __unicode__(self):
		return str(self.image)

class EquipmentType(models.Model):
	"""A sort of equipment, for example: 'Xenon Fantastico Projector'"""
	name = models.CharField(max_length=1024, null=False, blank=False)
	provider = models.TextField(null=True, blank=True)
	url = models.URLField(verify_exists=False, blank=True, null=True, max_length=1024)
	notes = models.TextField(blank=True, null=True)
	@models.permalink
	def get_absolute_url(self):
		return ('art_cloud.front.views.equipment_type_detail', (), { 'id':self.id })
	class Meta:
		ordering = ['name']
	class HydrationMeta:
		attributes = ['id', 'name', 'provider', 'url']
		nodes = ['notes']
	def __unicode__(self):
		return self.name

class Equipment(models.Model):
	"""A piece of equipment like a projector or a ladder."""
	name = models.CharField(max_length=1024, null=False, blank=False)
	equipment_type = models.ForeignKey(EquipmentType, blank=False, null=False)
	photos = models.ManyToManyField(Photo, null=True, blank=True)
	notes = models.TextField(blank=True, null=True)
	@models.permalink
	def get_absolute_url(self):
		return ('art_cloud.front.views.equipment_detail', (), { 'id':self.id })
	class Meta:
		verbose_name_plural = 'equipment'
		ordering = ['name']
	class HydrationMeta:
		attributes = ['id', 'name']
		nodes = ['equipment_type', 'photos', 'notes']
	def __unicode__(self):
		return "%s: %s" % (self.equipment_type.name, self.name)

class Document(models.Model):
	"""A document associated with an Installation."""
	doc = models.FileField(upload_to='document', blank=False, null=False)
	title = models.CharField(max_length=1024, null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	def save(self, *args, **kwargs):
		"""When saving the content, use the title if one isn't provided"""
		if self.title == None or len(self.title) == 0: self.title = str(self.doc)
		if self.title.rfind('/') != -1: self.title = self.title[self.title.rfind('/') + 1:]
		super(Document, self).save(*args, **kwargs)
	def get_absolute_url(self):
		return self.doc.url
	class Meta:
		ordering = ['-created']
	def __unicode__(self):
		return str(self.doc)

class InstallationSite(models.Model):
	"""A location in which art is installed."""
	name = models.CharField(max_length=1024, null=False, blank=False)
	location = models.CharField(max_length=1024, null=True, blank=True)
	notes = models.TextField(blank=True, null=True)
	photos = models.ManyToManyField(Photo, null=True, blank=True)
	equipment = models.ManyToManyField(Equipment, null=True, blank=True)
	@models.permalink
	def get_absolute_url(self):
		return ('art_cloud.front.views.installation_site_detail', (), { 'id':self.id })
	class Meta:
		verbose_name =  'location'
		verbose_name_plural = 'locations'
		ordering = ['name']
	class HydrationMeta:
		attributes = ['id', 'name', 'location']
		nodes = ['notes', 'photos', 'equipment']
	def __unicode__(self):
		return self.name

class InstallationManager(models.Manager):
	def all_open(self):
		return self.filter(closed=None) | self.filter(closed__gt=datetime.datetime.now())
	def search(self, search_string):
		terms = normalize_search_string(search_string)
		if len(terms) == 0: return None;
		name_query = Installation.objects.filter(name__icontains=terms[0])
		for term in terms[1:]:
			name_query = name_query & Installation.objects.filter(name__icontains=term)
		search_query = name_query
		return search_query.order_by('name')

class Installation(models.Model):
	"""A piece of art"""
	name = models.CharField(max_length=1024, null=False, blank=False)
	slug = models.SlugField(blank=True, null=True)
	groups = models.ManyToManyField(ArtistGroup, null=True, blank=True)
	artists = models.ManyToManyField(User, null=True, blank=True)
	site = models.ForeignKey(InstallationSite, null=True, blank=True)
	opened = models.DateTimeField(null=True, blank=True)
	closed = models.DateTimeField(null=True, blank=True)
	notes = models.TextField(blank=True, null=True)
	photos = models.ManyToManyField(Photo, null=True, blank=True)
	wiki_name = models.CharField(max_length=255, blank=True, null=True)
	documents = models.ManyToManyField(Document, null=True, blank=True)

	objects = InstallationManager()

	def _get_tags(self):
		return Tag.objects.get_for_object(self)
	def _set_tags(self, tag_list):
		Tag.objects.update_tags(self, tag_list)
	tags = property(_get_tags, _set_tags)
	def _get_tag_names(self):
		return " ".join([tag.name for tag in self.tags])
	tag_names = property(_get_tag_names, _set_tags)

	def collaborators(self):
		q = User.objects.filter(installation=self) | User.objects.filter(artistgroup__installation=self)
		return q.distinct().order_by('username')
		
	def named_dates(self):
		return NamedDate.objects.get_for_object(self)

	def is_opened(self):
		if self.is_closed(): return False
		if self.opened == None: return False
		return self.opened < datetime.datetime.now()
	is_opened.boolean = True

	def is_closed(self):
		if self.closed == None: return False
		return self.closed < datetime.datetime.now()
	
	@models.permalink
	def get_absolute_url(self):
		if self.slug:
			return ('art_cloud.front.views.installation_detail_slug', (), { 'slug':self.slug })
		else:
			return ('art_cloud.front.views.installation_detail', (), { 'id':self.id })
	class Meta:
		verbose_name =  'artwork'
		verbose_name_plural = 'works of art'
		ordering = ['name']
	class HydrationMeta:
		attributes = ['id', 'name', 'slug', 'opened', 'closed', 'wiki_name']
		ref_attributes = ['site']
		nodes = ['groups', 'artists', 'notes', 'photos']
	def __unicode__(self):
		return self.name

class HeartbeatManager(models.Manager):
	def delete_old_heartbeats(self):
		deadline = datetime.datetime.now() - datetime.timedelta(days=2)
		for heartbeat in self.filter(created__lt=deadline):
			heartbeat.delete()

class Heartbeat(models.Model):
	"""A periodic message sent by an installation which is used to monitor their status."""
	installation = models.ForeignKey(Installation, null=False, blank=False)
	info = models.TextField(blank=True, null=True)
	created = models.DateTimeField(auto_now_add=True)
	
	objects = HeartbeatManager()
	
	def trimmed_info(self):
		if self.info: 
			if len(self.info) > 60:
				return self.info[:60] + '...'
			return self.info
		return None
	def timed_out(self):
		return self.created + datetime.timedelta(seconds=settings.HEARTBEAT_TIMEOUT) < datetime.datetime.now() 
	class Meta:
		ordering = ['-created']
	def __unicode__(self):
		return "%s: %s" % (self.installation, self.created)

class UserProfileManager(models.Manager):
	def notify_art_technician(self, subject, message_text):
		message = render_to_string('front/email/tech_notification.txt', { 'message': message_text })

art_cloud/front/forms.py
# Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
from django import forms
from django.contrib.auth.models import User
from django.utils.html import strip_tags

from models import *

class SearchForm(forms.Form):
	terms = forms.CharField(required=True)

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('display_name', 'bio', 'url', 'phone_number')

class ToggleInstallationOpenForm(forms.Form):
	"""Submitted to toggle whether the installation is opened"""
	installation_id = forms.IntegerField()
	opened = forms.BooleanField(required=False)

class NotesForm(forms.Form):
	"""Used by Installation and Equipment pages to update their notes."""
	notes = forms.CharField(required=False, widget=forms.Textarea())

class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('email',)

class PhotoForm(forms.ModelForm):
	class Meta:
		model = Photo

class DocumentForm(forms.ModelForm):
	class Meta:
		model = Document

class TagsForm(forms.Form):
	tags = forms.CharField(required=False)

art_cloud/front/templates/front/equipment_detail.html
{% extends "art_cloud/base.html" %}
{% load imagetags %}
{% load listtags %}
{% load debugtags %}
{% block sub-title %}{{ equipment.name }} | {% endblock %}

{% block sub-head %}
<script type="text/javascript">
function initialize(){
	$(".equipment-notes-widget").hide();
}
$(document).ready(function() { initialize(); });
</script>
{% endblock %}

{% block style %}
.equipment-notes-widget { 
	position: absolute; left; 20px; 
	background-color: #FFF; border: solid 2px #DDD;
	padding: 20px; 
}
{% endblock %}

{% block content%}
<h1><a href="{{ equipment.equipment_type.get_absolute_url }}">{{ equipment.equipment_type.name }}</a>: {{ equipment.name }}</h1>

<table>
	{% if equipment.installationsite_set.all %}
	<tr>
		<th>location{{ equipment.installationsite_set.all|pluralize }}:</th>
		<td>
			{% for site in equipment.installationsite_set.all %}
				<a href="{{ site.get_absolute_url }}">{{ site.name }}</a>{% loop_comma %}
			{% endfor %}
		</td>
	</tr>
	{% endif %}
	{% if equipment.notes or equipment_notes_form %}
	<tr>
		<th>notes:</th>
		<td>
			<pre class="equipment-notes" id="equipment-notes-{{ equipment.id }}">{{ equipment.notes }}</pre>
			{% if equipment_notes_form %}
			<div class="equipment-notes-widget" id="equipment-notes-widget-{{ equipment.id }}">
				<div style="float: right;">
					[<a href="." onclick="$('#equipment-notes-widget-{{ equipment.id }}').hide(); $('#equipment-notes-{{ equipment.id }}').show(); return false;">close</a>]
				</div>
				<form action="." method="post">
					{% for field in equipment_notes_form %}{{ field}}{% endfor %}
					<input type="hidden" name="equipment_form_id" value="{{ equipment.id }}" />
					<input type="submit" value="save note" />
					{% csrf_token %}
				</form>
			</div>
			[<a href="." onclick="$('#equipment-notes-{{ equipment.id }}').hide(); $('#equipment-notes-widget-{{ equipment.id}}').show(); return false">edit</a>]
			{% endif %}
		</td>
	</tr>
	{% endif %}
</table>

{% endblock %}

/* Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. */

art_cloud/front/templates/front/equipment_type_detail.html
{% extends "art_cloud/base.html" %}
{% load imagetags %}
{% load listtags %}

{% block sub-title %}{{ equipment_type.name }} | {% endblock %}

{% block sub-head %}
<script type="text/javascript">
function initialize(){
	$(".equipment-type-notes-widget").hide();
}
$(document).ready(function() { initialize(); });
</script>
{% endblock %}

{% block style %}
.equipment-type-notes-widget { 
	position: absolute; left; 20px; 
	background-color: #FFF; border: solid 2px #DDD;
	padding: 20px; 
}
{% endblock %}

{% block content%}
<h1>{{ equipment_type.name }}</h1>

<table>
	{% if equipment_type.provider %}
	<tr><th>provider:</th><td>{{ equipment_type.provider }}</td></tr>
	{% endif %}
	{% if equipment_type.url %}
	<tr><th>url:</th><td>{{ equipment_type.url|urlize }}</a></td></tr>
	{% endif %}
	{% if equipment_type.notes or equipment_type_notes_form %}
	<tr>
		<th>notes:</th>
		<td>
			<pre class="equipment-type-notes" id="equipment-type-notes-{{ equipment_type.id }}">{{ equipment_type.notes }}</pre>
			{% if equipment_type_notes_form %}
			<div class="equipment-type-notes-widget" id="equipment-type-notes-widget-{{ equipment_type.id }}">
				<div style="float: right;">
					[<a href="." onclick="$('#equipment-type-notes-widget-{{ equipment_type.id }}').hide(); $('#equipment-type-notes-{{ equipment_type.id }}').show(); return false;">close</a>]
				</div>
				<form action="." method="post">
					{% for field in equipment_type_notes_form %}{{ field}}{% endfor %}
					<input type="hidden" name="equipment_type_form_id" value="{{ equipment_type.id }}" />
					<input type="submit" value="save note" />
					{% csrf_token %}
				</form>
			</div>
			[<a href="." onclick="$('#equipment-type-notes-{{ equipment_type.id }}').hide(); $('#equipment-type-notes-widget-{{ equipment_type.id}}').show(); return false">edit</a>]
			{% endif %}
		</td>
	</tr>
	{% endif %}
</table>
{% if equipment_type.equipment_set.all %}
	<h3>Equipment of this type:</h3>
	<ul>
	{% for equipment in equipment_type.equipment_set.all %}
		<li><a href="{{ equipment.get_absolute_url }}">{{ equipment.name }}</a></li>
	{% endfor %}
	</ul>
{% endif %}

{% endblock %}

/* Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. */

art_cloud/front/templates/front/heartbeats.html
{% extends "art_cloud/base.html" %}
{% load imagetags %}
{% load clue %}

{% block sub-title %}Heartbeats | {% endblock %}

{% block style %}
.expired-td { background-color: #FF6666; }
.unexpired-td { background-color: #66FF66; }
#heartbeat-table tr {  border: solid 5px #FFF; }
#heartbeat-table td { padding: 0px 10px; }
.heartbeat-item { margin: 10px 10px; }
{% endblock %}

{% block page_help_icon %}{% include "clue/page_help_icon.frag" %}{% endblock %}
{% block page_help %}{% help_text "heartbeats" %}{% endblock %}

{% block content%}
<h1>Heartbeats:</h1>

<h2>Latest:</h2>
<table id="heartbeat-table">
{% for installation in installations %}
	{% if not installation.is_closed %}
	<tr>
		<th><a href="{% url front.views.installation_heartbeats installation.id %}">{{ installation.name }}</a></th>
		{% with installation.heartbeat_set.all|first as heartbeat %}
		<td {% if not heartbeat or heartbeat.timed_out %}class="expired-td"{% else %}class="unexpired-td"{% endif %}>
			{{ heartbeat.created|date:"F j \a\t g:i A" }}
		</td>
		{% endwith %}
	</tr>
	{% endif %}
{% endfor %}	
</table>

<h2>Stream:</h2>
{% for heartbeat in heartbeats|slice:":60" %}
	{% ifchanged heartbeat.created.day %}<h3>{{ heartbeat.created|date:"F j" }}</h3>{% endifchanged %}
	{% with "true" as trim_info %}{% include "front/heartbeat_item.frag" %}{% endwith %}
{% endfor %}

{% endblock %}

/* Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. */

art_cloud/front/templates/front/help_slice.html
{% extends "front/base-index.html" %}
{% load imagetags %}
{% load clue %}

{% block sub-style %}
#slice-tabs #help-tab { background-color: #EEE; }
{% endblock %}

{% block slice%}

{% help_text "front page" %}

{% endblock %}

/* Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. */

art_cloud/front/templates/front/installation_detail.html
{% extends "art_cloud/base.html" %}
{% load imagetags %}
{% load listtags %}
{% load clue %}
{% block sub-title %}{{ installation.name }} | {% endblock %}

{% block sub-head %}
<link rel="stylesheet" type="text/css" href="/admin-media/css/widgets.css" />
<script type="text/javascript" src="/admin/jsi18n/"></script>
<link href="/media/art_cloud/admin.css" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="/admin-media/js/core.js"></script>
<script type="text/javascript" src="/admin-media/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/admin-media/js/calendar.js"></script>
<script type="text/javascript" src="/admin-media/js/admin/DateTimeShortcuts.js"></script>

<script type="text/javascript">

function showAddNamedDateForm(){ $("#add-named-date").show(); $("#id_name").focus(); }
function hideAddNamedDateForm(){ $("#add-named-date").hide(); }

function initialize(){
	$("#error-message").hide();
	$("#tag-form").hide();
	$(".installation-notes-widget").hide();
	$("#error-message").show("slide", { direction: "up" }, 1000);
	setTimeout("hideErrorMessage();", 5000);
}
$(document).ready(function() { initialize(); });

function hideErrorMessage(){
	$("#error-message").hide("slide", { direction: "down" }, 1000);
}

</script>
{% endblock %}

{% block style %}
h4 { margin-top: 20px; }
#id_tags { width: 400px; }
#add-named-date, .installation-notes-widget { 
	position: absolute; left; 20px; 
	background-color: #FFF; border: solid 2px #DDD;
	padding: 20px; 
}
{% endblock %}

{% block page_help_icon %}{% include "clue/page_help_icon.frag" %}{% endblock %}
{% block page_help %}{% help_text "installation detail" %}{% endblock %}


{% block content%}
<h1>Artwork: {{ installation.name }}</h1>

{% if error_message %}
<div id="error-message">{{ error_message }}</div>
{% endif %}

{% with request.user.is_staff as edit_tags %}{% with "true" as hide_title %}{% include "front/installation_item.frag" %}{% endwith %}{% endwith %}

{% endblock %}

/* Copyright 2009 GORBET + BANERJEE (http://www.gorbetbanerjee.com/) Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. */